# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 87baa508d6c0dbfc9bbe88d55a3079e84a7f28085265f7ec528824fbc45e97dbaa99b42e94b70b9dd50c4e269909496ba5dd8988928701cc9cdf9ace91deb8fe

test:
  secret_key_base: 7bbf132fb1ddca472e5ae120c720efd3e99903100899a3334cc9e1b40ee22c26b8b8736d71f2ab2eb0254bacaf2a62f20bc4e3af7e33a248a38011009dd48dea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
